package com.kirtan.companion.data

import kotlin.math.abs
import kotlin.math.floor
import kotlin.math.ln
import kotlin.math.pow
import kotlin.math.roundToInt

/**
 * The pure tuning facts — no UI, no audio, no storage behind them.
 *
 * Ported from `src/data/tuning.js`, which is GENERATED by
 * `scripts/analyzeTuning.mjs`. That script is the source of truth for the
 * measured numbers below: if the sample recordings change, re-run
 * `npm run analyze-tuning` in the web project and copy the two
 * [END_BASE_FREQ] values across. They must not drift between platforms, or the
 * same cents offset names a different note on each.
 *
 * Same contract pattern as [EQ_BANDS]: the engine's clamp, the mixer's
 * slider/readout and persistence's load-time sanitise all read here, so the
 * three can't drift apart.
 */

/**
 * Per-end tuning bounds in cents. ±600 reaches EVERY key: no starting pitch is
 * more than a tritone from its nearest target note.
 */
const val TUNE_MIN_CENTS = -600
const val TUNE_MAX_CENTS = 600

/**
 * Measured open-stroke fundamentals in Hz (median over analysis windows, then
 * over the round-robin variants). The bayan number is its strike resonance — a
 * nominal reference rather than a clean pitch.
 */
val END_BASE_FREQ: Map<String, Double> = mapOf(
    "dayan" to 641.8,
    "bayan" to 79.9,
)

/** Cents offset → playback rate ratio. */
fun centsToRate(cents: Int): Double = 2.0.pow(cents / 1200.0)

fun clampCents(cents: Int): Int = cents.coerceIn(TUNE_MIN_CENTS, TUNE_MAX_CENTS)

private val NOTE_NAMES = listOf(
    "C", "C♯", "D", "D♯", "E", "F", "F♯", "G", "G♯", "A", "A♯", "B",
)

/**
 * Frequency → nearest note name plus residual cents, e.g. "E5 −12¢". The
 * residual keeps the readout honest when the drum sits between semitones, which
 * a hand-tuned drum usually does.
 *
 * The minus sign is U+2212, matching the web readout exactly.
 */
fun freqToNoteName(freq: Double): String {
    val n = 69 + 12 * (ln(freq / 440.0) / ln(2.0))
    val nearest = n.roundToInt()
    val cents = ((n - nearest) * 100).roundToInt()
    val name = NOTE_NAMES[((nearest % 12) + 12) % 12] + (floor(nearest / 12.0).toInt() - 1)
    return if (cents == 0) name else "$name ${if (cents > 0) "+" else "−"}${abs(cents)}¢"
}
