package com.kirtan.companion.data

import com.kirtan.companion.data.model.LaneId
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * The maintainer export.
 *
 * The point of these tests is that the export must be PASTABLE: a snippet that
 * does not compile is worse than no snippet, because it looks authoritative and
 * the mistake surfaces as a build failure hours later in a different file. So
 * escaping, literal shape and field completeness are all asserted here.
 *
 * The strongest check is the first one: exporting a built-in must reproduce the
 * literals that beat is defined by. The shipped set is generated by
 * `scripts/generateBuiltinBeats.mjs`, so if these diverge the generator and the
 * exporter disagree about the same data — which is exactly the drift this file
 * exists to catch.
 */
class BeatSourceExportTest {

    /** The first shipped beat, and the only one with a cymbal row. */
    private val doubleTime = BEATS.first { it.id == "double_time_2" }

    @Test
    fun `exporting a built-in reproduces the notations it is defined by`() {
        assertEquals("X-OOX-OOX-OOX-OO", BeatSourceExport.patternNotation(doubleTime, LaneId.DAYAN))
        assertEquals("O--X-OO-O--X-OO-", BeatSourceExport.patternNotation(doubleTime, LaneId.BAYAN))
        assertEquals("O-XXO-XXO-XXO-XX", BeatSourceExport.patternNotation(doubleTime, LaneId.KARTAL))
    }

    @Test
    fun `a beat with no cymbals has no kartal notation at all`() {
        // "No cymbals" is an ABSENT lane, not an all-rest one, so the notation is
        // empty rather than a row of dashes — and the exporters must not emit a
        // kartal line for it.
        val tehai = BEATS.first { it.id == "tehai" }
        assertEquals("", BeatSourceExport.patternNotation(tehai, LaneId.KARTAL))
        assertNull(tehai.pattern(LaneId.KARTAL))
    }

    @Test
    fun `the exported pattern notation agrees with the share codec's`() {
        // Two independent encoders of the same grid. If they drift, a beat pasted
        // out of one path would not mean the same thing through the other. This
        // now covers compound meters too: `matan` is 48 cells over 24 quarters.
        for (beat in BEATS) {
            val decoded = ShareCodec.decodeShare(ShareCodec.encodeBeat(beat))
            assertTrue(decoded is ShareCodec.SharePayload.BeatPayload)
            val round = (decoded as ShareCodec.SharePayload.BeatPayload).beat

            for (lane in LaneId.ORDERED) {
                val exported = BeatSourceExport.patternNotation(beat, lane)
                val viaCodec = round.pattern(lane)
                    ?.joinToString("") { it?.code ?: ShareCodec.REST_CHAR }
                if (beat.pattern(lane) == null) {
                    // An absent lane exports as "" but the codec deliberately
                    // materialises every lane as all-rests on decode, so the two
                    // can only be compared for lanes the beat actually has.
                    assertEquals("${beat.id}/${lane.wireId}: an absent lane exported a notation", "", exported)
                    continue
                }
                assertEquals(
                    "${beat.id}/${lane.wireId}: export and share codec disagree",
                    viaCodec,
                    exported,
                )
            }
        }
    }

    @Test
    fun `a built-in round-trips through the share format unchanged`() {
        // The generator derives steps/beatsPerBar/cellsPerGroup the same way the
        // decoder does, so encode-then-decode must return the identical meter.
        // If it did not, a beat shared from this app would play differently on
        // the web.
        for (beat in BEATS) {
            val payload = ShareCodec.decodeShare(ShareCodec.encodeBeat(beat))
            val round = (payload as ShareCodec.SharePayload.BeatPayload).beat
            assertEquals("${beat.id}: steps", beat.steps, round.steps)
            assertEquals("${beat.id}: beatsPerBar", beat.beatsPerBar, round.beatsPerBar, 0.0)
            assertEquals("${beat.id}: cellsPerGroup", beat.cellsPerGroup, round.cellsPerGroup)
            assertEquals("${beat.id}: groups", beat.groups, round.groups)
            assertEquals("${beat.id}: bpm", beat.bpm, round.bpm)
        }
    }

    @Test
    fun `the kotlin export carries every field the share format strips`() {
        // id, group and description are exactly what ShareCodec refuses to carry,
        // and exactly what replacing a baked-in entry needs. This beat is given a
        // description because the shipped set has none.
        val withProse = doubleTime.copy(
            description = "Forward doubled into sixteenths.",
        )
        val source = BeatSourceExport.toKotlinSource(withProse)

        assertTrue(source.contains("id = \"double_time_2\""))
        assertTrue(source.contains("group = \"Sixteenths\""))
        assertTrue(source.contains("description = \"Forward doubled into sixteenths.\""))
        assertTrue(source.contains("name = \"Double Time 2\""))
        assertTrue(source.contains("note = \"4 beats\""))
        assertTrue(source.contains("bpm = 140"))
        // Groups and cpq, not steps/beatsPerBar/cellsPerGroup: those are derived.
        assertTrue(source.contains("groups = listOf(4, 4, 4, 4)"))
        assertTrue(source.contains("cpq = 4"))
        assertTrue(source.contains("dayan = \"X-OOX-OOX-OOX-OO\""))
        assertTrue(source.contains("bayan = \"O--X-OO-O--X-OO-\""))
        assertTrue(source.contains("kartal = \"O-XXO-XXO-XXO-XX\""))
        assertTrue(source.trimEnd().endsWith("),"))
    }

    @Test
    fun `a beat with no prose exports no description line`() {
        val source = BeatSourceExport.toKotlinSource(doubleTime)
        assertFalse("emitted a description for a beat that has none", source.contains("description ="))
        assertFalse(BeatSourceExport.toJsSource(doubleTime).contains("description: \""))
    }

    @Test
    fun `a beat with no cymbals exports no kartal line`() {
        val kotlin = BeatSourceExport.toKotlinSource(BEATS.first { it.id == "tehai" })
        assertTrue(kotlin.contains("// no kartal line"))
        assertFalse(kotlin.contains("kartal ="))
        assertFalse(BeatSourceExport.toJsSource(BEATS.first { it.id == "tehai" }).contains("kartal:"))
        assertFalse(
            BeatSourceExport.toJson(BEATS.first { it.id == "tehai" })["p"].toString().contains("kartal")
        )
    }

    @Test
    fun `a whole bar length is exported without a decimal point`() {
        // The Kotlin export does not carry beatsPerBar at all — builtIn derives it
        // from groups and cpq — so this checks the two places that do: the JS
        // object and the JSON. `4.0` beside entries that all say `4` is noise;
        // `3.5` must stay fractional where the meter really is.
        assertTrue(BeatSourceExport.toJsSource(doubleTime).contains("beatsPerBar: 4,"))
        assertTrue(BeatSourceExport.toJson(doubleTime).toString().contains("\"beatsPerBar\":4.0"))

        val sevenEight = doubleTime.copy(
            id = null, groups = listOf(2, 2, 3), steps = 7, beatsPerBar = 3.5,
            lanePatterns = doubleTime.lanePatterns.mapValues { (_, cells) -> cells.take(7) },
        )
        val kotlin = BeatSourceExport.toKotlinSource(sevenEight)
        assertTrue("the uneven groups were not exported: $kotlin", kotlin.contains("groups = listOf(2, 2, 3)"))
        assertTrue(kotlin.contains("cpq = 2"))
        assertTrue(BeatSourceExport.toJsSource(sevenEight).contains("beatsPerBar: 3.5,"))
    }

    @Test
    fun `the js export uses the array form the web file is written in`() {
        val source = BeatSourceExport.toJsSource(doubleTime)

        assertTrue(source.contains("id: \"double_time_2\","))
        assertTrue(source.contains("group: \"Sixteenths\","))
        // The generator now writes groups into beats.js, so the export must too —
        // a hand-written entry that omitted them would re-derive a different bar.
        assertTrue(source.contains("groups:"))
        assertTrue(
            source.contains(
                "dayan: [\"X\",null,\"O\",\"O\",\"X\",null,\"O\",\"O\",\"X\",null,\"O\",\"O\",\"X\",null,\"O\",\"O\"],"
            )
        )
    }

    @Test
    fun `the json export is machine-readable and keeps the stripped fields`() {
        val json = BeatSourceExport.toJson(doubleTime)

        assertEquals("double_time_2", (json["id"] as JsonPrimitive).content)
        assertEquals("Sixteenths", (json["group"] as JsonPrimitive).content)
        assertEquals(16, (json["steps"] as JsonPrimitive).content.toInt())
        assertEquals(4.0, (json["beatsPerBar"] as JsonPrimitive).content.toDouble(), 0.0)
        assertNotNull(json["groups"])

        val patterns = json["p"] as JsonObject
        assertEquals("X-OOX-OOX-OOX-OO", (patterns["dayan"] as JsonPrimitive).content)
    }

    @Test
    fun `hostile characters in a name or description cannot break the literal`() {
        // A straight double quote would terminate the string early, and a `$`
        // would start a Kotlin template — either turns a pasted snippet into a
        // compile error in a file the user did not write.
        val nasty = doubleTime.copy(
            id = null,
            name = "Quote \" and backslash \\ and dollar \$ end",
            description = "Line one\nLine two\tTabbed",
        )

        val kotlin = BeatSourceExport.toKotlinSource(nasty)
        assertTrue(kotlin.contains("\\\""))
        assertTrue(kotlin.contains("\\\\"))
        assertTrue(kotlin.contains("\\\$"))
        assertTrue(kotlin.contains("\\n"))

        val js = BeatSourceExport.toJsSource(nasty)
        assertTrue(js.contains("\\\""))
        assertTrue(js.contains("\\n"))
    }

    @Test
    fun `an absent optional field exports as null, not as an empty string`() {
        val minimal = doubleTime.copy(id = null, group = null, description = null)

        val json = BeatSourceExport.toJson(minimal)
        assertEquals("null", json["id"].toString())
        assertEquals("null", json["group"].toString())
        assertEquals("null", json["description"].toString())

        val kotlin = BeatSourceExport.toKotlinSource(minimal)
        assertTrue(kotlin.contains("id = null"))
        assertTrue(kotlin.contains("group = null"))
        assertFalse(kotlin.contains("description ="))

        val js = BeatSourceExport.toJsSource(minimal)
        assertTrue(js.contains("id: null"))
        assertTrue(js.contains("description: null"))
    }

    @Test
    fun `a custom beat from the editor exports cleanly`() {
        // The realistic path: author in the editor, export, paste over a built-in.
        var draft = com.kirtan.companion.ui.editor.EditorDraft.from(null)
        val ta = com.kirtan.companion.ui.editor.padSetFor(
            com.kirtan.companion.ui.editor.EditLane.BOTH
        ).first { it.key == "ta" }
        repeat(4) { draft = draft.tapPad(ta) }

        val beat = draft.toBeat(null)
        val source = BeatSourceExport.toKotlinSource(beat)

        assertTrue(source.contains("id = null"))
        assertTrue(source.contains("name = \"Custom Beat\""))
        assertTrue(source.contains("group = null"))
        assertTrue(source.contains("dayan = \"OOOO----\""))
        assertNull(beat.id)
    }
}
