package com.kirtan.companion.data

import com.kirtan.companion.data.model.LaneId
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.int
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Wire compatibility with the web encoder, checked against REAL vectors.
 *
 * `src/test/resources/share-vectors.json` is generated by running the web app's
 * own `src/data/shareCodec.js` under Node (see the generator in the repo's
 * scripts). It is not a hand-written expectation: the codes in it are the bytes
 * the browser produces today, and links built from them are already in
 * circulation.
 *
 * The first test below is the one that matters most. A shared beat carries no id,
 * so the recipient's library resolves built-in ids against ITS OWN compiled
 * list — which means the two platforms must agree byte for byte or the same link
 * silently encodes a different beat on each. Asserting equality of the encoded
 * STRING, rather than of the decoded structure, is what makes that impossible to
 * miss: any drift in key order, number formatting or lane omission fails here.
 *
 * REGENERATE the fixture after changing either codec:
 *   node scripts/generateShareVectors.mjs
 */
class ShareCodecWireTest {

    private val fixture: JsonObject by lazy {
        val stream = javaClass.getResourceAsStream("/share-vectors.json")
            ?: error("share-vectors.json missing from test resources")
        Json.parseToJsonElement(stream.bufferedReader().use { it.readText() }).jsonObject
    }

    private val beatVectors: JsonArray get() = fixture["beats"]!!.jsonArray

    // ── Encoding ───────────────────────────────────────────────────────────

    @Test
    fun `kotlin encoder is byte-identical to the web encoder for every built-in beat`() {
        for (vector in beatVectors) {
            val obj = vector.jsonObject
            val id = obj["id"]!!.jsonPrimitive.content
            val expectedCode = obj["code"]!!.jsonPrimitive.content

            val beat = BEATS.firstOrNull { it.id == id }
            assertNotNull("no built-in beat with id \"$id\" — the two lists have diverged", beat)

            assertEquals(
                "encoded share code for \"$id\" differs from the web encoder",
                expectedCode,
                ShareCodec.encodeBeat(beat!!),
            )
        }
    }

    @Test
    fun `kotlin encoder matches the web encoder for a category`() {
        val cat = fixture["category"]!!.jsonObject
        val ids = listOf("te_ta", "forward", "prabhupada")
        val beats = ids.map { id -> BEATS.first { it.id == id } }

        assertEquals(
            cat["code"]!!.jsonPrimitive.content,
            ShareCodec.encodeCategory(cat["name"]!!.jsonPrimitive.content, beats),
        )
    }

    // ── Decoding ───────────────────────────────────────────────────────────

    @Test
    fun `every web-encoded beat decodes to the beat the web decoder produced`() {
        for (vector in beatVectors) {
            val obj = vector.jsonObject
            val id = obj["id"]!!.jsonPrimitive.content
            val code = obj["code"]!!.jsonPrimitive.content

            val payload = ShareCodec.decodeShare(code)
            assertTrue(
                "web code for \"$id\" was rejected by the Kotlin decoder",
                payload is ShareCodec.SharePayload.BeatPayload,
            )
            val beat = (payload as ShareCodec.SharePayload.BeatPayload).beat

            // The web decoder's own output is the expectation.
            val expected = obj["decoded"]!!.jsonObject["beat"]!!.jsonObject
            assertEquals(expected["name"]!!.jsonPrimitive.content, beat.name)
            assertEquals(expected["note"]!!.jsonPrimitive.content, beat.note)
            assertEquals(expected["bpm"]!!.jsonPrimitive.int, beat.bpm)
            assertEquals(expected["steps"]!!.jsonPrimitive.int, beat.steps)
            assertEquals(expected["beatsPerBar"]!!.jsonPrimitive.int.toDouble(), beat.beatsPerBar, 0.0)
            assertEquals(expected["cellsPerGroup"]!!.jsonPrimitive.int, beat.cellsPerGroup)

            val expectedGroups = expected["groups"]!!.jsonArray.map { it.jsonPrimitive.int }
            assertEquals(expectedGroups, beat.groups)

            // Patterns, lane by lane, against the web decoder's arrays.
            for (lane in LaneId.ORDERED) {
                val expectedCells = expected[lane.wireId]?.jsonArray
                val actual = beat.pattern(lane)
                if (expectedCells == null) {
                    assertNull("lane ${lane.wireId} should be absent for \"$id\"", actual)
                    continue
                }
                assertNotNull("lane ${lane.wireId} missing for \"$id\"", actual)
                assertEquals(
                    "lane ${lane.wireId} of \"$id\"",
                    expectedCells.map { if (it is JsonPrimitive && it.content != "null") it.content else null },
                    actual!!.map { it?.code },
                )
            }

            // An id is NEVER taken from a payload — it is minted on import.
            assertNull("a decoded beat must not carry an id", beat.id)
        }
    }

    @Test
    fun `a category decodes to all of its beats or none`() {
        val cat = fixture["category"]!!.jsonObject
        val payload = ShareCodec.decodeShare(cat["code"]!!.jsonPrimitive.content)
        assertTrue(payload is ShareCodec.SharePayload.CategoryPayload)
        val beats = (payload as ShareCodec.SharePayload.CategoryPayload).beats

        val expected = cat["decoded"]!!.jsonObject["beats"]!!.jsonArray
        assertEquals(expected.size, beats.size)
        expected.forEachIndexed { i, e ->
            assertEquals(e.jsonObject["name"]!!.jsonPrimitive.content, beats[i].name)
            assertEquals(e.jsonObject["steps"]!!.jsonPrimitive.int, beats[i].steps)
        }
    }

    @Test
    fun `decoding is the exact inverse of encoding for a built-in beat`() {
        for (beat in BEATS) {
            val payload = ShareCodec.decodeShare(ShareCodec.encodeBeat(beat))
            assertTrue(payload is ShareCodec.SharePayload.BeatPayload)
            val round = (payload as ShareCodec.SharePayload.BeatPayload).beat

            assertEquals(beat.name, round.name)
            assertEquals(beat.bpm, round.bpm)
            assertEquals(beat.steps, round.steps)
            assertEquals(beat.beatsPerBar, round.beatsPerBar, 0.0)
            assertEquals(groupsFor(beat), round.groups)
            for (lane in LaneId.ORDERED) {
                assertEquals(
                    "lane ${lane.wireId} of ${beat.id}",
                    beat.pattern(lane)?.map { it?.code },
                    round.pattern(lane)?.map { it?.code },
                )
            }
        }
    }

    // ── The trust boundary ─────────────────────────────────────────────────

    /**
     * Every hostile vector must either be REJECTED outright or, if accepted,
     * satisfy the invariants the boundary promises.
     *
     * Asserting the invariants rather than a per-case expected outcome is
     * deliberate: it tests what the boundary GUARANTEES, so a vector added later
     * is covered without anyone remembering to state its answer. These are the
     * properties that make an imported beat safe to store and render.
     */
    @Test
    fun `hostile payloads are rejected or stripped to something safe`() {
        val vectors = fixture["hostile"]!!.jsonArray
        assertTrue("no hostile vectors in the fixture", vectors.isNotEmpty())

        for (vector in vectors) {
            val obj = vector.jsonObject
            val why = obj["why"]!!.jsonPrimitive.content
            val code = obj["code"]!!.jsonPrimitive.content

            val payload = ShareCodec.decodeShare(code)

            if (payload == null || payload is ShareCodec.SharePayload.Invalid) continue

            val beats = when (payload) {
                is ShareCodec.SharePayload.BeatPayload -> listOf(payload.beat)
                is ShareCodec.SharePayload.CategoryPayload -> payload.beats
                else -> continue
            }

            for (beat in beats) {
                assertNull("$why: an id must never come from a payload", beat.id)
                assertNull("$why: description must be dropped, not validated", beat.description)
                assertNull("$why: group must be dropped, not validated", beat.group)
                assertTrue("$why: bpm escaped its bounds (${beat.bpm})", beat.bpm in MIN_BPM..MAX_BPM)
                assertTrue("$why: steps escaped its DoS bound (${beat.steps})", beat.steps in 1..ShareCodec.MAX_STEPS)
                assertTrue("$why: name escaped its cap", beat.name.length <= ShareCodec.MAX_NAME_LEN)
                assertTrue(
                    "$why: name still carries control or format characters",
                    !Regex("[\\p{Cc}\\p{Cf}]").containsMatchIn(beat.name),
                )
                // Reading patterns by lane id is an allowlist: a payload key we
                // do not know can never become a lane.
                assertTrue(
                    "$why: an unknown lane key became a lane",
                    beat.lanePatterns.keys.all { it in LaneId.ORDERED },
                )
                for (cells in beat.lanePatterns.values) {
                    assertEquals("$why: pattern length disagrees with steps", beat.steps, cells.size)
                }
            }
        }
    }

    @Test
    fun `an absurd bpm is clamped rather than rejected`() {
        val vector = fixture["hostile"]!!.jsonArray.first {
            it.jsonObject["why"]!!.jsonPrimitive.content == "bpm absurd, must clamp not reject"
        }.jsonObject

        val payload = ShareCodec.decodeShare(vector["code"]!!.jsonPrimitive.content)
        assertTrue("a clamped field must not cause rejection", payload is ShareCodec.SharePayload.BeatPayload)
        assertEquals(
            vector["expectClampedBpm"]!!.jsonPrimitive.int,
            (payload as ShareCodec.SharePayload.BeatPayload).beat.bpm,
        )
    }

    @Test
    fun `invisible characters are stripped from an imported name`() {
        val vector = fixture["hostile"]!!.jsonArray.first {
            it.jsonObject["why"]!!.jsonPrimitive.content == "name with control + format chars"
        }.jsonObject

        val payload = ShareCodec.decodeShare(vector["code"]!!.jsonPrimitive.content)
        assertTrue(payload is ShareCodec.SharePayload.BeatPayload)
        assertEquals(
            vector["expectName"]!!.jsonPrimitive.content,
            (payload as ShareCodec.SharePayload.BeatPayload).beat.name,
        )
    }

    // ── Cheap checks first ─────────────────────────────────────────────────

    @Test
    fun `oversized and non-alphabet codes never reach the decoder`() {
        assertNull(ShareCodec.decodeShare(null))
        assertNull(ShareCodec.decodeShare(""))
        assertNull(ShareCodec.decodeShare("A".repeat(ShareCodec.MAX_CODE_LEN + 1)))
        // Characters outside base64url: a URL-encoder mistake, or a probe.
        assertNull(ShareCodec.decodeShare("abc+def=="))
        assertNull(ShareCodec.decodeShare("abc def"))
    }

    @Test
    fun `a pasted whole URL yields the same code as a bare one`() {
        val code = ShareCodec.encodeBeat(BEATS.first())
        assertEquals(code, ShareCodec.codeFromInput("https://kirtan.example/#b=$code"))
        assertEquals(code, ShareCodec.codeFromInput("  #b=$code  "))
        assertEquals(code, ShareCodec.codeFromInput(code))
    }
}
